### ISSUE TITLE
Wildcard state shows HTTP error instead of nice error message (or empty results)

### ISSUE THREAD

**Issue by derekatkins** [TonyLHansen/atastandings#2]
I was playing around and trying to ask for results from "all districts" and, later, "all states", but the results were... different.  If I try to request "all districts" in the usual Unix way I get a nice error message telling me the valid options:
```
$ atastandings -d \* -c BCOB
atastandings: error: argument -d/--district: invalid choice: '*' (choose from dict_keys(['Mid-America', 'Midwest', 'North', 'Northeast', 'Northwest', 'Southeast', 'South', 'Southwest', 'Rockies']))
```
on the other hand, doing this with a state results in an http error:
```
$ atastandings  -S \* -c BCOB
STATE STANDINGS FOR *, maximum place of 99
Accessing https://atamartialarts.com/events/tournament-standings/state-standings/?country=US&state=*&code=BCOB returned the status code 500
```
If instead of an asterisk I give an invalid state code, I just get empty data (as mostly expected):
```
$ atastandings -S cy -c BCOB
STATE STANDINGS FOR CY, maximum place of 99
```

**Comment by TonyLHansen** [comment]
`--state xyz` should have generated an error message comparable to `--district xyz`

**Comment by TonyLHansen** [comment]
fix pushed
