### ISSUE TITLE
Feature Request:  only use cached data without trying to (re)check its validity

### ISSUE THREAD

**Issue by derekatkins** [TonyLHansen/atastandings#7]
It would be nice to have a feature to skip the web downloads completely and just used the cached data.  I.e., it would act as if all cached data has been recently checked as current.
This would be useful over the summer, when the website never changes, to speed up the "first" run in a while (I don't know what the default cache validity time is).
It would also be useful down the road because I plan to cache data by week, so I'd like to "just use it".

The -T option is part of what I want, but it still wants to go re-validate the cache.  I want an option to just assume the cache is valid without even checking.

ETA: Looking at the code, it certainly looks like -T is doing what I want -- but the first run after a while still takes a long time!  I wonder if it's just taking a while to stat all 811 cache files and bring them into RAM?

**Comment by TonyLHansen** [comment]
check out -T option. If this isn't sufficient, please add another comment.
```
  -T, --ignore-cache-times
                        Do not timeout any existing cache of the web pages.
```

**Comment by derekatkins** [comment]
I think the issue is RAM Cache from "disk" after an extended period of non-use..  
I've been using -T in all my executions.
What I was seeing was a significant delay the first time I'd run atastandings (after a while), and then it would be very fast subsequent executions.  This led me to believe it was going back to the website.  However another possibility is a delay in stat()ing 800+ files.  So after waiting > 24 hours I did a `cat webcache/* > /dev/null ; find webcache -ls > /dev/null` before running atastandings -T, and the first run was as fast as I would expect.
What I don't understand is why it would be so slow from Python whereas cat / find are fast..  My system has SSD (actually NVE).  So "reading from disk" should be nearly instantaneous.

**Comment by TonyLHansen** [comment]
I've changed --dots to output a ":" when it is going to the web and a "." when using the cache. So if you turn on --dots, you can see for certain when it is doing one versus the other.
